repeat wait() until game:IsLoaded()
wait(10)
local player = game:GetService("Players").LocalPlayer
local humanoid = player.Character and player.Character:FindFirstChild("Humanoid")
local desiredPlaceID = 14363263080
local currentPlaceID = game.PlaceId


local function moveAndWait(position)
    if humanoid then
        humanoid:MoveTo(position)
        humanoid.MoveToFinished:Wait()
    end
end

if currentPlaceID == desiredPlaceID then
moveAndWait(Vector3.new(2825, 31, -2071))
moveAndWait(Vector3.new(2804, 31, -2084))
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
moveAndWait(Vector3.new(2825, 31, -2071))
moveAndWait(Vector3.new(2807, 31, -2091))
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(2)
moveAndWait(Vector3.new(2721, 25, -2159))
moveAndWait(Vector3.new(2673, 25, -2187))
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2569, 8, -2250)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(2651, 25, -2168))
moveAndWait(Vector3.new(2633, 25, -2164))
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2585, 8, -2306)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(2)
moveAndWait(Vector3.new(2586, 8, -2237))
moveAndWait(Vector3.new(2590, 8, -2292))
moveAndWait(Vector3.new(2570, 8, -2350))
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2536, 8, -2482)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2570, 8, -2482)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(1)
moveAndWait(Vector3.new(2552, 8, -2560))
moveAndWait(Vector3.new(2552, 20, -2604))
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
task.wait(6.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(Vector3.new(2623, 66, -2700)))
local player, character, humanoid, targetPart = game.Players.LocalPlayer, (game.Players.LocalPlayer.Character or game.Players.LocalPlayer.CharacterAdded:Wait()), (game.Players.LocalPlayer.Character:WaitForChild("Humanoid")), workspace.Map.Structures.Boss1Zone.LanternHanging["Cylinder.006"]; local function lookAtTarget() humanoid.Parent:SetPrimaryPartCFrame(CFrame.new(humanoid.Parent.Head.Position, humanoid.Parent.Head.Position + (targetPart.Position - humanoid.Parent.Head.Position).unit)) end; lookAtTarget()
task.wait(7)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(43)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(3)
moveAndWait(Vector3.new(2518, 38, -2735))
moveAndWait(Vector3.new(2444, 62, -2733))
wait(1)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2237, 62, -2748)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(3)
moveAndWait(Vector3.new(2243, 62, -2749))
moveAndWait(Vector3.new(2174, 102, -2750)) -- doing somthing
wait(1)
local player, character, humanoid, targetPart = game.Players.LocalPlayer, (game.Players.LocalPlayer.Character or game.Players.LocalPlayer.CharacterAdded:Wait()), (game.Players.LocalPlayer.Character:WaitForChild("Humanoid")), workspace.Map.Structures.Lighting:GetChildren()[10]["Cube.002"]; local function lookAtTarget() humanoid.Parent:SetPrimaryPartCFrame(CFrame.new(humanoid.Parent.Head.Position, humanoid.Parent.Head.Position + (targetPart.Position - humanoid.Parent.Head.Position).unit)) end; lookAtTarget()
task.wait(2)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2075, 117, -2769)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(3)
moveAndWait(Vector3.new(2068, 117, -2739))
moveAndWait(Vector3.new(1994, 159, -2748))
moveAndWait(Vector3.new(1994, 159, -2760))
task.wait(.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(1867, 173, -2780)))
task.wait(.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(7)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(3)
moveAndWait(Vector3.new(1994, 159, -2760))
moveAndWait(Vector3.new(1962, 172, -2765))
moveAndWait(Vector3.new(1854, 173, -2790))
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(1917, 173, -2716)))
task.wait(1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.5)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(3)
moveAndWait(Vector3.new(1905, 173, -2761))
moveAndWait(Vector3.new(1907, 213, -2861))
task.wait(.3) -- boss fight
while pcall(function() return workspace.dungeon.room6.enemyFolder["Sangor, the Bloodthirsty"] end) and workspace.dungeon.room6.enemyFolder["Sangor, the Bloodthirsty"] do if workspace.dungeon.room6.enemyFolder["Sangor, the Bloodthirsty"] then game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, workspace.dungeon.room6.enemyFolder["Sangor, the Bloodthirsty"].Head.Position)) wait(0.3) game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game) game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game) wait(6.3) else break end end
moveAndWait(Vector3.new(1910, 228, -3002))
moveAndWait(Vector3.new(1915, 240, -3103))
moveAndWait(Vector3.new(1949, 241, -3120))
task.wait(.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(1915, 228, -3185)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(7)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(1950, 228, -3228)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(7)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(1948, 240, -3108))
moveAndWait(Vector3.new(1925, 240, -3108))
moveAndWait(Vector3.new(1925, 228, -3128))
moveAndWait(Vector3.new(1919, 228, -3214))
moveAndWait(Vector3.new(1889, 230, -3224))  -- problem 1
task.wait(.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, workspace.dungeon.room7.enemyFolder:GetChildren()[39].Head.Position))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(7)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, workspace.dungeon.room7.enemyFolder:GetChildren()[39].Head.Position))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(1929, 228, -3221))
moveAndWait(Vector3.new(1945, 228, -3263))  -- problem 2
task.wait(.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(1969, 228, -3304)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(7)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(1964, 228, -3311)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(8)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(1971, 228, -3395))
moveAndWait(Vector3.new(2006, 228, -3384)) -- problem 3
task.wait(.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2046, 228, -3403)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(10)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2051, 228, -3397)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(8)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(2078, 228, -3417)) -- problem 4
task.wait(.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2131, 228, -3424)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(9.2)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(7)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2128, 228, -3431)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(8.1) -- problem again 5
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(2185, 228, -3453))
task.wait(.5)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2228, 228, -3428)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(9)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, Vector3.new(2256, 228, -3424)))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(8)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(4)
moveAndWait(Vector3.new(2289, 228, -3426))
moveAndWait(Vector3.new(2296, 228, -3400))
moveAndWait(Vector3.new(2350, 228, -3333))  -- boss 3
task.wait(.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, workspace.dungeon.room9.enemyFolder["Commander Leonaru"].Head.Position))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(6.3)
game.Players.LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(game.Players.LocalPlayer.Character.HumanoidRootPart.Position, workspace.dungeon.room9.enemyFolder["Commander Leonaru"].Head.Position))
task.wait(.3)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.Q, false, game)
game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.E, false, game)
task.wait(.5)


else
print('no')
end